language: go

go:
  - 1.9.x

sudo: required
dist: trusty

matrix:
    include:
        - os: linux
        - os: osx

branches:
    only:
        - master
        - development
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get install p7zip-full
    else
      brew update-reset
      brew install p7zip
    fi
  - go get golang.org/x/oauth2
  - go get github.com/google/go-github/github

script:
  - go build
  - go test github.com/d1vanov/ciuploadtool/uploader

after_success:
    - |
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        export CIUPLOADTOOL_NAME=ciuploadtool_linux
      else
        export CIUPLOADTOOL_NAME=ciuploadtool_mac
      fi
      7z a ${CIUPLOADTOOL_NAME}.zip ciuploadtool &&
      ./ciuploadtool -suffix=$TRAVIS_BRANCH ${CIUPLOADTOOL_NAME}.zip
