version: '0.1.0-{build}'

branches:
  only:
    - master
    - development
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

environment: 
  auth_token:
    secure: bFPozfVngJ8Gonjmldc8N5leBx7PxwwYIqnK/bpSsPVUYqEYHafBBQRwrtdL+oc9
  matrix:
    - prepare_mode: YES
    - prepare_mode: NO
      platform: x86
    - prepare_mode: NO
      platform: x64

clone_folder: c:\gopath\src\github.com\d1vanov\ciuploadtool

init:
  - set GOPATH=c:\gopath
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%

install:
  - go get golang.org/x/oauth2
  - go get github.com/google/go-github/github

build_script:
  - go build
  - go test github.com/d1vanov/ciuploadtool/uploader
  - if %prepare_mode%==YES ciuploadtool.exe -suffix="%APPVEYOR_REPO_BRANCH%" -preponly
  - ps: if ($env:prepare_mode -eq "YES") { throw "Failing in order to stop the current build matrix job early" }
  - set CIUPLOADTOOL_ARCHIVE_NAME=ciuploadtool_windows_%platform%.zip
  - 7z a %CIUPLOADTOOL_ARCHIVE_NAME% ciuploadtool.exe

artifacts:
  - path: '*.zip'
    name: ciuploadtool

on_finish:
  - ciuploadtool.exe -suffix="%APPVEYOR_REPO_BRANCH%" "%CIUPLOADTOOL_ARCHIVE_NAME%"

matrix:
  allow_failures:
    - prepare_mode: YES
